language: node_js
node_js:
  - "0.10"
after_success:
 - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec --require spec/helper.js
 - cat ./coverage/lcov.info | node_modules/.bin/coveralls

notifications:
  slack:
    rooms:
    - secure: "EDzz2GOhCVIjM9HdZrvESSPNnJoppsbFO3xX4XdORm1U1/76lwBBkVsZ6N9PzntsWyFhRigey1LJT610K7FaMtK5zRwhIe7pkuY+d3x9nWzCWjE10L1IfBscgr9wXuMuRAkMZbOjzQq5ZyeUCJ/YC9b1krBSNu0lr6WqSPJQ7qO32+CuTLh8HFyOFPIMbkAEYL9SIYI1544N9Pd/oi2qUo2S59Oirm8h+821MjtPFAvHd9PHiCOX+AhlEGR7whIw7Ha1RYfEQanHtb08zfDIX+Lhrxn4VXulysdi2JA0TrP3wWlJNOZiEKof/DIa4W/mG+A0j5vDQOY32nmmh8TLbipR/88Ojm7EJqLsd6OmoWBT6lFVfcwvvxhjoRkMWPZsJYbJGUzNqRxv6Hu078VQOXw1+MvZQTmQ7oF5WUQoEmnL+QsKeu/dm3yfrTkFbRj+PqFI9QoVmMKoifyo9QFPpcS/8JTxdZTF2JemTaJADYm9OrCDtvERlqwv5atm+TrHClRrE1DPmuUk3x/4Yj5sirv8WHKOHwtU0v8/fHmj1Txgo7nS+vfizo8oVoVjMaE91GMSkx6eLUFRyuQCm8ey9osvSsx3ssoCugjQ/xIsHPC/zJg83M2i82gp29aHbWl0EmootBRq6iRbtZ9ncnccAg1eRaI2zavKGSExmkpUmug="
